import streamlit as st
from quizlet import md_to_txt
from quizlet import clean_data
import learn

def home():
    st.session_state.clear()
    show_folders()

def show_folders():
    """
    Show all of the folders as clickable buttons
    """
    obsidian = md_to_txt()
    folders = []
    for vault in obsidian:
        if vault not in st.session_state:
            folders.append(vault)
            st.session_state[vault] = False

    def hide_folders(dir, obsidian=obsidian):
        """
        Hide all of the folders

        Parameters
        ----------
        dir : str
            Name of clicked directory

        Returns
        -------
        dir : str
            Name of clicked directory
        """
        for f in folders:
            st.session_state[f] = False
        show_files(dir)
    
    for f in folders:
        if not st.session_state[f]:
            st.button(f, width="stretch", on_click=hide_folders, args=[f])

def show_files(dir):
    """
    Show all of the files of folder as clickable buttons

    Parameters
    ----------
    dir : str
            Name of clicked directory
    """
    st.button("Back", on_click=home)
    obsidian = md_to_txt()
    file_names = []
    file_paths = []
    for vault, subvault in obsidian.items():
        if vault == dir:
            for file_name in subvault:
                file_names.append(file_name)
                file_paths.append(subvault[file_name])
                if file_name not in st.session_state:
                    st.session_state[file_name] = False

    def hide_files(index, subdir, dir=dir):
        """
        Hide all of the files

        Parameters
        ----------
        index : int
            Index of clicked subdirectory
        subdir : str
            Name of clicked subdirectory
        dir : str
            Name of clicked directory

        Returns
        -------
        file_path : str
            Location of clicked subdirectory
        subdir : str
            Name of file
        dir : str
            Name of clicked directory
        """
        for f in file_names:
            st.session_state[f] = False
        file_path = file_paths[index]
        show_data(file_path, subdir, dir)

    for i, f in enumerate(file_names):
        if not st.session_state[f]:
            st.button(f, width="stretch", on_click=hide_files, args=[i, f])

def show_data(file_path, subdir, dir):
    """
    Show all of the file data on webpage as markdown

    Parameters
    ----------
    file_path : str
        Location of clicked subdirectory
    subdir : str
            Name of file
    dir : str
        Name of clicked directory
    """
    def preconfigure_settings(file_path, subdir, dir):
        """
        Send file_path for possible dismiss and call configure_settings

        Parameters
        ----------
        file_path : str
            Location of clicked subdirectory
        """
        handle_dismiss(file_path)
        configure_settings(file_path, subdir, dir)

    st.title(subdir)
    left, middle, right = st.columns(3)
    folders = left.button("Home", width="stretch", on_click=home)
    files = middle.button(dir, width="stretch", on_click=show_files, args=[dir])
    learn = right.button("Learn", width="stretch", on_click=preconfigure_settings, args=[file_path, subdir, dir])

    with open(file_path, "r") as file:
        data = file.read()
    st.markdown(data)

def handle_dismiss(file_path):
    pass

@st.dialog("Settings", width="small", dismissible=True)
def configure_settings(file_path, subdir, dir):
    """
    Show all of the learning options

    Parameters
    ----------
    file_path : str
        Location of clicked subdirectory
    subdir : str
        Name of file
    dir : str
        Name of clicked directory
    """

    def save_settings(file_path, is_shuffle, ques_type, answ_type):
        """
        Show all of the learning options

        Parameters
        ----------
        file_path : str
            Location of clicked subdirectory
        is_shuffle : bool
            Randomize the data or not
        ques_type : str
            Type of question generated by the computer
        answ_type : str
            Type of answer generated by the client
        """
        if ques_type == "Flashcards":
            learn.learn_flashcards(file_path, is_shuffle, answ_type)
        elif ques_type == "Multiple choice":
            learn.learn_choice(file_path, is_shuffle, answ_type)
        elif ques_type == "Write":
            learn.learn_write(file_path, is_shuffle, answ_type)
        elif ques_type == "Test":
            learn.learn_test(file_path, is_shuffle, answ_type)

    is_shuffle = st.toggle("Shuffle")
    ques_type = st.radio("Question type", ["Flashcards", "Multiple choice", "Write", "Test"])
    answ_type = st.radio("Answer type", ["Term", "Definition"])

    left, right = st.columns(2)
    left.button("Back", width="stretch", on_click=show_data, args=[file_path, subdir, dir])
    right.button("Start", width="stretch", on_click=save_settings, args=[file_path, is_shuffle, ques_type, answ_type])

def main():
    show_folders()

if __name__ == "__main__":
    main()
