import streamlit as st
from quizlet import md_to_txt
from quizlet import clean_data
from app import configure_settings
import random

def learn():
    pass

def shuffle():
    """
    Randomize data

    Parameters
    ----------
    data : dict
        Dictionary whose keys are terms and values are definitions
    seen : list
        List of terms whose elements are the terms that have been seen

    Returns
    -------
    seen : list
        List of terms whose elements are the terms that have been seen
    """
    data = clean_data()
    term = random.choice(st.session_state["unseen"])
    definition = data[term]

    st.session_state["unseen"].remove(term)
    st.session_state["seen"].append(term)

    return term, definition

def learn_flashcards(file_path, subdir, dir, is_shuffle, answ_type):
    """
    Repeatedly loop through the data until mastered

    Parameters
    ----------
    file_path : str
        Location of clicked subdirectory
    subdir : str
        Name of clicked subdirectory
    dir : str
        Name of clicked directory
    is_shuffle : bool
        Randomize the data or not
    answ_type : str
        Type of answer generated by the client
    """
    data = clean_data(file_path)
    if "index" not in st.session_state:
        st.session_state["index"] = 0
    if "flip" not in st.session_state:
        st.session_state["flip"] = False
    if "next" not in st.session_state:
        st.session_state["next"] = False
    if "back" not in st.session_state:
        st.session_state["back"] = False
    if "unseen" not in st.session_state:
        st.session_state["unseen"] = [data.keys()]
    if "seen" not in st.session_state:
        st.session_state["seen"] = []
    
    def flip_flashcard(card):
        """
        Flip the flashcard
        """
        if card == "front":
            back()
        else:
            front()

    def increment_flashcard():
        """
        Show the next flashcard
        """
        st.session_state["index"] += 1
        front()

    def decrement_flashcard():
        """
        Show the previous flashcard
        """
        if st.session_state["index"] > 0:
            st.session_state["index"] -= 1
        front()

    def front():
        st.progress(st.session_state["index"] / len(data))
        left, middle, right = st.columns(3)
        left.button("⬅️", width="stretch", on_click=decrement_flashcard)
        middle.button("Flip", width="stretch", on_click=flip_flashcard, args=["front"])
        right.button("➡️", width="stretch", on_click=increment_flashcard)
    
        if st.session_state["index"] < len(data):
            # if is_shuffle:
            #     data = clean_data()
            #     term = random.choice(st.session_state["unseen"])
            #     st.session_state["unseen"].remove(term)
            #     st.session_state["seen"].append(term)
            #     definition = data[term]
            # else:
            i = st.session_state["index"]
            term = list(data)[i]
            definition = data[term]
            st.write(term)
        else:
            st.session_state["index"] = 0
            configure_settings(file_path, subdir, dir)

    def back():
        st.progress(st.session_state["index"] / len(data))
        left, middle, right = st.columns(3)
        left.button("⬅️", width="stretch", on_click=decrement_flashcard)
        middle.button("Flip", width="stretch", on_click=flip_flashcard, args=["back"])
        right.button("➡️", width="stretch", on_click=increment_flashcard)
    
        if st.session_state["index"] < len(data):
            i = st.session_state["index"]
            term = list(data)[i]
            definition = data[term]
            st.write(definition)
        else:
            st.session_state["index"] = 0
            configure_settings(file_path, subdir, dir)
    front()

def learn_choice(file_path, subdir, dir, is_shuffle, answ_type):
    """
    Repeatedly loop through the data until mastered

    Parameters
    ----------
    file_path : str
        Location of clicked subdirectory
    is_shuffle : bool
        Randomize the data or not
    answ_type : str
        Type of answer generated by the client
    """
    data = clean_data(file_path)

    def hide_choice():
        pass

    correct = []
    incorrect = []

def learn_write(file_path, subdir, dir, is_shuffle, answ_type):
    """
    Repeatedly loop through the data until mastered

    Parameters
    ----------
    file_path : str
        Location of clicked subdirectory
    subdir : str
        Name of clicked subdirectory
    dir : str
        Name of clicked directory
    is_shuffle : bool
        Randomize the data or not
    answ_type : str
        Type of answer generated by the client
    """
    data = clean_data(file_path)
    if "index" not in st.session_state:
        st.session_state["index"] = 0
    if "flip" not in st.session_state:
        st.session_state["flip"] = False
    if "next" not in st.session_state:
        st.session_state["next"] = False
    if "back" not in st.session_state:
        st.session_state["back"] = False
    if "correct" not in st.session_state:
        st.session_state["correct"] = [data.keys()]
    if "incorrect" not in st.session_state:
        st.session_state["incorrect"] = []

    def correct_write():
        """
        Show the next write
        """
        st.session_state["index"] += 1
        front()

    def incorrect_write():
        """
        Show the correct write
        """
        if st.session_state["index"] > 0:
            st.session_state["index"] -= 1
        front()

    def front():
        st.progress(st.session_state["index"] / len(data))
    
        if st.session_state["index"] < len(data):
            i = st.session_state["index"]
            term = list(data)[i]
            definition = data[term]
            st.write(term)
            st.text_input("")
        else:
            st.session_state["index"] = 0
            configure_settings(file_path, subdir, dir)

    def back():
        st.progress(st.session_state["index"] / len(data))
        left, middle, right = st.columns(3)
        left.button("⬅️", width="stretch", on_click=decrement_flashcard)
        middle.button("Flip", width="stretch", on_click=flip_flashcard, args=["back"])
        right.button("➡️", width="stretch", on_click=increment_flashcard)
    
        if st.session_state["index"] < len(data):
            i = st.session_state["index"]
            term = list(data)[i]
            definition = data[term]
            st.write(definition)
        else:
            st.session_state["index"] = 0
            configure_settings(file_path, subdir, dir)

    correct = []
    incorrect = []
    front()

def learn_test(file_path, subdir, dir, is_shuffle, answ_type):
    """
    Repeatedly loop through the data until mastered

    Parameters
    ----------
    file_path : str
        Location of clicked subdirectory
    is_shuffle : bool
        Randomize the data or not
    answ_type : str
        Type of answer generated by the client
    """
    data = clean_data(file_path)

    def hide_test():
        pass

    correct = []
    incorrect = []


def main():
    learn()

if __name__ == "__main__":
    main()
